#spring:
#  cloud:
#    gateway:
#      globalcors:
#        corsConfiguration:
#          '[/**]':
#            allowedOrigins: '*'
#            allowedHeaders: '*'
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE